# permissions for end users to view computejobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: computejob-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: distributed-job-scheduler-operator
    app.kubernetes.io/part-of: distributed-job-scheduler-operator
    app.kubernetes.io/managed-by: kustomize
  name: computejob-viewer-role
rules:
- apiGroups:
  - infra.openinnovation.ai
  resources:
  - computejobs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - infra.openinnovation.ai
  resources:
  - computejobs/status
  verbs:
  - get
