apiVersion: v1
entries:
  distributed-job-scheduler-operator:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2025-08-05T10:39:51.204972+05:30"
    description: A Helm chart for deploying distributed-job-scheduler-operator operator
    digest: 86c53f2ee19cb02e706dcca5e8ddbf1372063bd016d7fc37d4a7695bd5641d90
    name: distributed-job-scheduler-operator
    urls:
    - https://raw.githubusercontent.com/vishalanarase/openinnovationai/master/charts/distributed-job-scheduler-operator-0.1.1.tgz
    version: 0.1.1
  - apiVersion: v2
    appVersion: "1.0"
    created: "2025-08-05T10:39:51.204662+05:30"
    description: A Helm chart for deploying distributed-job-scheduler-operator operator
    digest: ad45afdf70f7c768a23e4efb7dcbdd23c0793e1e82f34f7c0bad248760a49d7a
    name: distributed-job-scheduler-operator
    urls:
    - https://raw.githubusercontent.com/vishalanarase/openinnovationai/master/charts/distributed-job-scheduler-operator-0.1.0.tgz
    version: 0.1.0
generated: "2025-08-05T10:39:51.203737+05:30"
