---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - infra.openinnovation.ai
  resources:
  - computejobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - infra.openinnovation.ai
  resources:
  - computejobs/finalizers
  verbs:
  - update
- apiGroups:
  - infra.openinnovation.ai
  resources:
  - computejobs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - infra.openinnovation.ai
  resources:
  - computenodes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - infra.openinnovation.ai
  resources:
  - computenodes/finalizers
  verbs:
  - update
- apiGroups:
  - infra.openinnovation.ai
  resources:
  - computenodes/status
  verbs:
  - get
  - patch
  - update
