apiVersion: infra.openinnovation.ai/v1
kind: ComputeJob
metadata:
  labels:
    app.kubernetes.io/name: computejob
    app.kubernetes.io/instance: computejob-sample
    app.kubernetes.io/part-of: distributed-job-scheduler-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: distributed-job-scheduler-operator
  name: computejob-sample
spec:
  command: "echo 'Hello, World!' && sleep 20 && exit 0"
  nodeSelector:
    kubernetes.io/hostname: kind-worker
  parallelism: 1
